### PR TITLE
Update zh_cn.lang & Change Punctuations: ’->'

### PR DESCRIPTION
**Pull request by Determancer**
For new version of TA.

### CODE REVIEW

**Comment by Determancer** [comment]
I saw 20 §l§n in the new text, but it seems that the underline is not very harmonius with the ink-style underline in thaumcraft itself.
Maybe it will be a good idea to keep all "§l" but to delete each "§n". Just a suggestion :)

**Comment by TechnoMysterio** [comment]
Thanks for the update PR, Codex can merge this when he gets the chance. Yeah in retrospect those extra underlines don't look amazing, I kinda went overboard with the formatting codes when I discovered that they actually work in the Thaumonomicon, so those can probably be removed.

**Comment by TheCodex6824** [comment]
Looks good so far, and yeah you can remove the extra underlines if you want to - as TechnoMysterio said we discovered that formatting codes actually work around when we were writing those entries, so they saw quite a bit of use around that time.

**Comment by Determancer** [comment]
By the way, thaumicaugmentation.research.void_stone.1 and thaumicaugmentation.research.void_stone.2 don't display in the game. It seems to be a code missing.

**Comment by TheCodex6824** [comment]
> By the way, thaumicaugmentation.research.void_stone.1 and thaumicaugmentation.research.void_stone.2 don't display in the game. It seems to be a code missing.

Are you sure? I believe those are for the variants of void stone (the tainted kind), not regular void stone. You need to scan each type individually to unlock their respective pages.

**Comment by Determancer** [comment]
> > By the way, thaumicaugmentation.research.void_stone.1 and thaumicaugmentation.research.void_stone.2 don't display in the game. It seems to be a code missing.
> 
> Are you sure? I believe those are for the variants of void stone (the tainted kind), not regular void stone. You need to scan each type individually to unlock their respective pages.

Sorry for bothering, I only used Cheater's Thaumonomicon and thought that all entries would be unlocked. After scanning they displayed now :P

**Comment by Determancer** [comment]
I wonder where the Furthur Infusion texts are at for I cannot find them @_@

**Comment by TechnoMysterio** [comment]
The entry for Further Infusion Studies is going to be added later since we first need to tidy up the placement of the existing entries.

**Pull request merged**
