### PR TITLE
Fix client impetus connection rendering after node reconnects

### PR DESCRIPTION
**Pull request by Srdjan-V**

### CODE REVIEW

**Comment by Srdjan-V** [comment]
Also forgot to mention if you want to test those behaviors in the future you can make those [if statements](https://github.com/TheCodex6824/ThaumicAugmentation/blob/master/src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java#L271) false

**Comment by Srdjan-V** [comment]
I have done some more testing, and i don't understand why but [this](https://github.com/TheCodex6824/ThaumicAugmentation/blob/bd7ef6f9c54938aace520652c81b528a3444e4b3/src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java#L274) seems to return null for some reason, causing the position to be removed from the node

**Comment by Srdjan-V** [comment]
The above was not correct, but i think that i have found the reason why this happening. Im connecting impetus generators in different chunks which might not be loaded by the time this [method](https://github.com/TheCodex6824/ThaumicAugmentation/blob/bd7ef6f9c54938aace520652c81b528a3444e4b3/src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/NodeHelper.java#L211) is called

To add more info the `protected Set<DimensionalBlockPos> inputs;` and `protected Set<DimensionalBlockPos> outputs;` fields of the relay and generator are being cleared

**Comment by Srdjan-V** [comment]
The above again didn't fix the issue(I might still be one), but i have found why the `DimensionalBlockPos` set's are getting cleared, after removing [thous](https://github.com/TheCodex6824/ThaumicAugmentation/blob/bd7ef6f9c54938aace520652c81b528a3444e4b3/src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java#L260) for loops, my world loaded without nodes disconnecting

**Comment by Srdjan-V** [comment]
I did some more testing and i was right the impetus generator is getting invalidated, and by extension clearing its connections
This is the stack trace:

```
[thaumicaugmentation]: Invalidating Impetus generator at BlockPos{x=-224, y=58, z=-99}, world.isRemote false
[thaumicaugmentation]: Printing stack trace:
[thaumicaugmentation]: 	thecodex6824.thaumicaugmentation.common.tile.TileImpetusGenerator.func_145843_s(TileImpetusGenerator.java:184)
[thaumicaugmentation]: 	net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:832)
[thaumicaugmentation]: 	net.minecraft.world.World.func_72939_s(World.java:1894)
[thaumicaugmentation]: 	net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[thaumicaugmentation]: 	net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[thaumicaugmentation]: 	net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[thaumicaugmentation]: 	net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)[thaumicaugmentation]: 	net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[thaumicaugmentation]: 	java.lang.Thread.run(Thread.java:750)```

**Comment by Srdjan-V** [comment]
I will be replacing most uses of tile entity invalidation with block invalidation

**Comment by TheCodex6824** [comment]
I'm going to have to read through everything here because I haven't had a chance to yet, but some initial questions / concerns:

- Is this still a symptom of the issue we were trying to fix in the last PR, or is it just completely broken?
- I originally did use the block break event long ago, but I had to stop because Thaumic Tinkerer and its tile entity moving thing crashed the game because it never called the break method. I assume most other tile-moving things would do the same, and I can't really fault a mod for having a *moving* thing not calling the *break* method.
- In your stack trace it looks like the `invalidate` call is coming from the tile entity being added to the chunk. I have to check the order things happen, but I thought that NBT got loaded after that. If that's not the case, then you can probably work around this by making the node destruction code in `invalidate` only run if the tile had at least 1 tick (you might be able to use whatever condition the `onAddedToWorld` method or whatever its called on the tile entity uses)

**Comment by Srdjan-V** [comment]
When i updated my world i saw that the original problem was still occurring, i went into dev to see if it would happen if the node never got added to the graph, the fix we added worked fine the only problem was that it was not syncing to the client, that was the original reason for the PR and the first commit. 

But after i updated it i tried it in my word and the original issue was still occurring, but this time the tileentity had its pos sets cleared, so after some digging, i found out that the invalidate method was being called, and that's clearing the pos set.

And yes the call is from the tileentity being added to the chunk, it checks if a tileentity exists at that position, if it exists it gets invalidated. I don't know how that is happening and its extremely difficult to debug

**Comment by Srdjan-V** [comment]
I have done some debugging and i think that i know what he cause is, but im still not 100% sure

The `ChunkIOProvider#syncCallback()` method is responsible  for loading tileentitys from disc, and i think that it gets triggered to early by immersive engineering.

The `onLoad` triggers the creating of a `FakePlayer` and in turn calling the `ChunkIOProvider`
image

The `onLoad` method of the gets called by this event, which is called before `IntegratedServer#loadAllWorlds.initialWorldChunkLoad()`
image

**Comment by TheCodex6824** [comment]
I'll give it a try with IE then and see if I can replicate it. I'll edit this after I try it.

**Comment by Srdjan-V** [comment]
Im using my modded instance, and connected it to my ide, that's the only way in able to reproduce this. And this is not dependent on the used mods(even after i have disabled the onLoad event listener of IE), after a point the load on the server gets to much for the server to handle and this weirdness starts happening.

For example, after creating a new save within the same instance it's working fine, but if i load into my save with a lot of entity's it starts disconnecting.

But either way, this isn't a bug with TA, other tiles are also getting invalidated, so we should just merge this pr and i will see if i can find a solution.

But one more thing i wanted to ask you, is this NodeHelper#validateFullGraph method really needed?

**Comment by TheCodex6824** [comment]
> But either way, this isn't a bug with TA, other tiles are also getting invalidated, so we should just merge this pr and i will see if i can find a solution.

I can't merge this as is, because of the issue I mentioned before with the game crashing if relying on the block break method to cleanup node connections. If I just remove the `invalidate` code, then there will be ghost connections left over, because the nodes the tile was connected to will still believe it has a connection to that location.

I just looked at the tile loading, and it looks like the *new* tile it is setting should have the NBT data (line 495 of `AnvilChunkLoader`). I would be interested to see what is calling `addTileEntity` and when - something might be trying to place a tile with no NBT.

> But one more thing i wanted to ask you, is this `NodeHelper#validateFullGraph` method really needed?

The condition leading to that call should never happen; it's there in case there is an inconsistency in the graph data (due to there being redundancy, because nodes store both their inputs and outputs). If that kind of situation is detected, there is a good chance things are dangerously broken, so that function just tries to fix things up as much as possible to salvage what it can. So to answer your question, it is not strictly necessary but is there in case there is a bug or other issue.

**Comment by Srdjan-V** [comment]
I didn't express myself clearly i wanted to what your thought where on the `NodeHelper#validateFullGraph` method are, and if where to be unnecessary i would have removed it in my next commit, since i was already planing to force push the changes i have made to the tile invalidation

>I would be interested to see what is calling addTileEntity and when - something might be trying to place a tile with no NBT.

The `World#updateEntities` at 1894, its invalidating the entity with it self

It gets loaded from nbt
image

And it gets invalidated later
image

**Comment by Srdjan-V** [comment]
I have found out the part that is causing the timing problem, if a event like the one from IE is loading chunks it has a chance that thay get added to the `World#addedTileEntityList`, in this lit its getting invalidated.

This in another example
image

**Comment by TheCodex6824** [comment]
Thanks for doing all of that investigative work - it appears that this is *not* a bug in IE. All it takes to reproduce this to to make the impetus nodes enter that tile list that you found. The easiest way to do this, and the way I replicated it, was to place some essentia tubes next to each other over a chunk border, and then connect up impetus nodes in those chunks. The connections were gone just as you were experiencing.

Now that I can actually make it happen, I can do some deep debugging and figure out how to work around this.

**Comment by Srdjan-V** [comment]
Glad to help, and also a quick and easy fix would be to check the stack trace, if it gets called from that method ignore the call to invalidate.

**Comment by TheCodex6824** [comment]
It appears that `Chunk#addTileEntity` is getting called twice for each tile - in `World#updateEntities` and `AnvilChunkLoader.loadEntities`. The call in `AnvilChunkLoader` happens first and correctly sets NBT, but unfortunately the overload of `addTileEntity` it calls (the one with just a tile) both adds the tile to the chunk, and adds it to the world. This sounds like what you would want, but when `processingLoadedTiles` is true, the tile gets added to a list for later. This means that when the world then calls `addTileEntity` with that tile, it is the same exact instance of the tile it added before - meaning that when it is invalidated, the NBT is just gone.

I would consider that a Forge bug, but as Forge for 1.12 has long been unsupported, it's my problem now.

> a quick and easy fix would be to check the stack trace, if it gets called from that method ignore the call to invalidate.

That would work (and I do use the stacktrace trick in some places), but I am concerned about the performance cost of creating potentially hundreds of stack traces in a single tick, which can be possible. As ugly as it might be, I might just use the coremod to patch in a check to that overload of `Chunk#addTileEntity` to not call its other overload when given a TA tile and instead just let the world deal with it later.

You mentioned before that all tiles are being invalidated like this - the vast majority of tiles don't do anything special when invalidated, so they should be fine. If you run into other tiles that are hit by this issue, let me know - I could expose a config option to make the fix occur for all tiles, not just mine. I normally don't like putting fixes like that in content mods, but since I have to coremod the game anyway, I might as well provide it.

**Comment by Srdjan-V** [comment]
I have talked to @Rongmario, he will be fixing this issue in [LoliASM](https://github.com/LoliKingdom/LoliASM). But for the time being you could use [this](https://github.com/CleanroomMC/Moshi-Moshi) for the stack trace

**Comment by Srdjan-V** [comment]
>and the way I replicated it, was to place some essentia tubes next to each other over a chunk border, and then connect up impetus nodes in those chunks

I have tried that and i could not replicate it, could you send a screenshot?

**Comment by TheCodex6824** [comment]
> I have tried that and i could not replicate it, could you send a screenshot?

setup

I should have specified that they have to be Thaumcraft essentia tubes, and not glass ones - pretty sure I made those not load chunks.

**Comment by Srdjan-V** [comment]
I have tried it just now, and i cant reproduce this (im trying it with your dev env)
image

**Comment by TheCodex6824** [comment]
The way I did it was making that setup, then flying off far to the right to make those chunks unload. Then when I fly back, all of the nodes lose their connections. You can also make it happen by closing and reopening the world, but the chunk you are standing in seems to affect which nodes get their connections removed. Lastly, make sure you aren't doing this in spawn chunks.

**Comment by Srdjan-V** [comment]
Its a bit finicky to get the expected result, but yea i managed to reproduce it.
Also This is probably a better visualization if the problem
image

**Comment by TheCodex6824** [comment]
When you get a chance, give the latest commit a try - it should finally fix all of the node disconnection issues.

**Comment by Srdjan-V** [comment]
I have tested it and its working fine

**Pull request merged**
