### PR TITLE
Update zh_cn.lang

### PR DESCRIPTION
**Pull request by Determancer**
All new entries.

### CODE REVIEW

**Comment by TheCodex6824** [comment]
Somebody else also asked about helping with a Chinese translation, so I asked them to take a look at this. I'll merge it after their feedback.

**Comment by Determancer** [comment]
> Somebody else also asked about helping with a Chinese translation, so I asked them to take a look at this. I'll merge it after their feedback. Also, thank you so much for taking the time to translate the new entries - I know it's a lot, but hopefully more people will get to appreciate it now that it's in their language!

That will be nice, and thanks for your notification, I will wait for them to review this.

**Comment by Determancer** [comment]
btw, is this the one who you mentioned as someone helping with translation?

**Comment by TheCodex6824** [comment]
> btw, is this the one who you mentioned as someone helping with translation?

No, it was someone that sent me an email a little while ago. To be fair, I didn't answer it for over a week (yeah pretty bad, I know...) due to being busy with schoolwork, so I would be a bit of a hypocrite if I didn't give them the same amount of time it took me to get caught up with things.

**Comment by TheCodex6824** [comment]
There's going to be an emergency release soonish due to a bad lag bug that was found, so I'm going to merge this now to get the translations in. If the person wants to help with the translation, they can make a new PR or send me another email with their feedback.

**Comment by Determancer** [comment]
@TheCodex6824 I download 2.0.9, but it seems like the zh_cn.lang is still the old file...
Only 229 lines are in it, which is the data of the last time.

**Pull request merged**
